'''
Created on Mar 3, 2015

@author: bstaley
'''

from collections import namedtuple


ScienceFileSearchParameters = namedtuple('ScienceFileSearchParameters',
                                         ['instrument',
                                          'levels',
                                          'plans',
                                          'groups',
                                          'descs',
                                          'exts',
                                          'ver',
                                          'rev',
                                          'file_name',
                                          'as_inv_file',
                                          'uprev_inv_file',
                                          'label_ver',
                                          'label_rev'])

all_key = 'all'
ancillary_key = 'anc'
event_key = 'evt'
instrument_config = {'acc':
                     ScienceFileSearchParameters(instrument='acc',
                                                 levels=['l3'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['tab', 'xml'],
                                                 ver=None,
                                                 rev=None,
						                          file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'acc-meta':
                     ScienceFileSearchParameters(instrument='acc',
                                                 levels=[],
                                                 plans=['metadata'],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'rse':
                     ScienceFileSearchParameters(instrument='rse',
                                                 levels=['l3'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['txt', 'xml', 'dat', 'pdf', 'tab'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     ancillary_key:
                     ScienceFileSearchParameters(instrument='anc',
                                                 levels=[],
                                                 plans=['eps', 'gnc', 'imu', 'ngms', 'pf', 'pte', 'rec', 'rs', 'sasm1', 'sasm2', 'sasm3', 'sff', 'svt', 'usm1', 'usm2', 'usm3', 'usm4', 'usm5', 'usm6'],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['drf', 'txt', 'sff'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'euv':
                     ScienceFileSearchParameters(instrument='euv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['cdf', 'dat', 'xml', 'drf', 'png', 'fits', 'gz'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     event_key:
                     ScienceFileSearchParameters(instrument='evt',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'iuv-derived':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file='',
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'iuv-derived-occultation':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_derived_occultation_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-derived-corona':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_derived_corona_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-derived-disk':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_derived_disk_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-derived-limb':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_derived_limb_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-processed-occultation':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_processed_occultation_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-processed-corona':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_processed_corona_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-processed-disk':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_processed_disk_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-processed-echelle':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_processed_echelle_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-processed-limb':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_processed_limb_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-occultation':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_occultation_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-corona':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_corona_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-cruise':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_cruise_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-disk':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_disk_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-limb':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_limb_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-ech':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_echelle_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-transition':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_transition_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-phobos':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_phobos_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-calibrated-calibration':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_calibrated_calibration_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
		            'iuv-raw-occultation':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_occultation_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-corona':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_corona_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-cruise':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_cruise_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-disk':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_disk_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-limb':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_limb_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-ech':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_echelle_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-transition':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_transition_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-phobos':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_phobos_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
                     'iuv-raw-calibration':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_raw_calibration_inventory.tab",
                                                 uprev_inv_file=True,
                                                 label_ver=1,
                                                 label_rev=0),
		             'iuv':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=['l0'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'iuv-meta':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=['metadata'],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'insitu-kp':
                     ScienceFileSearchParameters(instrument='kp',
                                                 levels=['insitu'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['tab'],
                                                 ver=15,
                                                 rev=5,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'iuv-kp':
                     ScienceFileSearchParameters(instrument='iuv',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/iuv/metadata/collection_maven_iuvs_kp_data_inventory.tab",
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'lpw':
                     ScienceFileSearchParameters(instrument='lpw',
                                                 levels=['l0b', 'l2'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['cdf', 'dat', 'xml', 'drf', 'png', 'fits', 'gz'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'mag':
                     ScienceFileSearchParameters(instrument='mag',
                                                 levels=['l2'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'ngi':
                     ScienceFileSearchParameters(instrument='ngi',
                                                 levels=['l0'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'ngi-l1a':
                     ScienceFileSearchParameters(instrument='ngi',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/ngi/metadata/collection_ngims_l1a_inventory.csv",
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'ngi-l1b':
                     ScienceFileSearchParameters(instrument='ngi',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/ngi/metadata/collection_ngims_l1b_inventory.csv",
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'ngi-l2':
                     ScienceFileSearchParameters(instrument='ngi',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/ngi/metadata/collection_ngims_l2_inventory.csv",
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'ngi-l3':
                     ScienceFileSearchParameters(instrument='ngi',
                                                 levels=[],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file="/maven/data/sci/ngi/metadata/collection_ngims_l3_inventory.csv",
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'ngi-meta':
                     ScienceFileSearchParameters(instrument='ngi',
                                                 levels=[],
                                                 plans=['metadata'],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'pfp':
                     ScienceFileSearchParameters(instrument='pfp',
                                                 levels=['l0'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=[],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'sep':
                     ScienceFileSearchParameters(instrument='sep',
                                                 levels=['l2'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['cdf', 'dat', 'xml', 'drf', 'png', 'fits', 'gz'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                    'sep-anc':
                     ScienceFileSearchParameters(instrument='sep',
                                                 levels=['anc'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['cdf', 'sav'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'sta':
                     ScienceFileSearchParameters(instrument='sta',
                                                 levels=['l2'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['cdf', 'dat', 'xml', 'drf', 'png', 'fits', 'gz'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'swe':
                     ScienceFileSearchParameters(instrument='swe',
                                                 levels=['l2'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['xml', 'cdf', 'md5'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     'swi':
                     ScienceFileSearchParameters(instrument='swi',
                                                 levels=['l2'],
                                                 plans=[],
                                                 groups=[],
                                                 descs=[],
                                                 exts=['cdf', 'dat', 'xml', 'drf', 'png', 'fits', 'gz'],
                                                 ver=None,
                                                 rev=None,
                                                 file_name=None,
                                                 as_inv_file=False,
                                                 uprev_inv_file=False,
                                                 label_ver=None,
                                                 label_rev=None),
                     }


'''
Update LID mapping to be static

lid - Mapping from file name to PDS4 compliant LID
'''
instrument_dictionary = {
    # Accelerometer
    'acc':
        {'lid': {'urn:nasa:pds:maven.acc.bundle:data': 'mvn_acc_l3_*'}},

    'anc':
        {'lid': {'urn:nasa:pds:maven.anc.drf:data.eps': 'mvn_anc_eps',
                 'urn:nasa:pds:maven.anc.drf:data.gnc': 'mvn_anc_gnc',
                 'urn:nasa:pds:maven.anc.drf:data.imu': 'mvn_anc_imu',
                 'urn:nasa:pds:maven.anc.drf:data.ngms': 'mvn_anc_ngms',
                 'urn:nasa:pds:maven.anc.drf:data.pf': 'mvn_anc_pf',
                 'urn:nasa:pds:maven.anc.drf:data.pte': 'mvn_anc_pte',
                 'urn:nasa:pds:maven.anc.drf:data.rec': 'mvn_anc_rec',
                 'urn:nasa:pds:maven.anc.drf:data.rs': 'mvn_anc_rs',
                 'urn:nasa:pds:maven.anc.drf:data.sasm1': 'mvn_anc_sasm1',
                 'urn:nasa:pds:maven.anc.drf:data.sasm2': 'mvn_anc_sasm2',
                 'urn:nasa:pds:maven.anc.drf:data.sff': 'mvn_anc_sff',
                 'urn:nasa:pds:maven.anc.drf:data.svt': 'mvn_anc_svt',
                 'urn:nasa:pds:maven.anc.drf:data.usm1': 'mvn_anc_usm1',
                 'urn:nasa:pds:maven.anc.drf:data.usm2': 'mvn_anc_usm2',
                 'urn:nasa:pds:maven.anc.drf:data.usm3': 'mvn_anc_usm3',
                 'urn:nasa:pds:maven.anc.drf:data.usm4': 'mvn_anc_usm4',
                 'urn:nasa:pds:maven.anc.drf:data.usm5': 'mvn_anc_usm5',
                 'urn:nasa:pds:maven.anc.drf:data.usm6': 'mvn_anc_usm6',
                 'urn:nasa:pds:maven.anc.events:data.all': 'mvn_anc_all',
                 'urn:nasa:pds:maven.anc.events:data.orbnum': 'mvn_anc_orbnum'}},

    # Extreme UV Spectrometer
    'euv':
        {'lid': {'urn:nasa:pds:maven.euv.calibrated:data.bands': 'mvn_euv_l2_bands',
                 'urn:nasa:pds:maven.euv.modelled:data.daily.spectra': 'mvn_euv_l3_daily',
                 'urn:nasa:pds:maven.euv.modelled:data.minute.spectra': 'mvn_euv_l3_minute'}},
    
    # Radio occultation science experiment
    'rse':
        {'lid': {'urn:nasa:pds:maven.rose.raw:data.tnf': 'mvn_rse_l0_tnf',
                 'urn:nasa:pds:maven.rose.raw:data.rsr': 'mvn_rse_l0_rsr',
                 'urn:nasa:pds:maven.rose.raw:calibration.dlf': 'mvn_rse_l2_dlf',
                 'urn:nasa:pds:maven.rose.calibrated:calibration.fup': 'mvn_rse_l2_fup',
                 'urn:nasa:pds:maven.rose.calibrated:data.sky': 'mvn_rse_l2_sky',
                 'urn:nasa:pds:maven.rose.derived:data.edp': 'mvn_rse_l3_edp',
                 'urn:nasa:pds:maven.rose.raw:browse.bro': 'mvn_rse_l0_bro',
                 'urn:nasa:pds:maven.rose.raw:calibration.ion': 'mvn_rse_l3_ion',
                 'urn:nasa:pds:maven.rose.raw:calibration.tro': 'mvn_rse_l3_tro',
                 'urn:nasa:pds:maven.rose.raw:calibration.wea': 'mvn_rse_l2_(w10|w40|w60).*'}},

    # IUV
    'iuv':
        {'lid': {'urn:nasa:pds:maven.iuvs.raw:calibration': 'mvn_iuv_l1a_(centroid|star).*',
                 'urn:nasa:pds:maven.iuvs.raw:corona': 'mvn_iuv_l1a_(outbound|inbound|inspace|outspace|incorona|outcorona).*',
                 'urn:nasa:pds:maven.iuvs.raw:cruise': 'mvn_iuv_l1a_(checkout|ISON|IPH|cruisecal).*',
                 'urn:nasa:pds:maven.iuvs.raw:disk': 'mvn_iuv_l1a_(apoapse|outdisk|indisk).*',
                 'urn:nasa:pds:maven.iuvs.raw:echelle': 'mvn_iuv_l1a_.*ech.*',
                 'urn:nasa:pds:maven.iuvs.raw:limb': 'mvn_iuv_l1a_(periapse|outlimb|inlimb).*',
                 'urn:nasa:pds:maven.iuvs.raw:occultation': 'mvn_iuv_l1a_occultation.*',
                 'urn:nasa:pds:maven.iuvs.raw:phobos': 'mvn_iuv_l1a_(phobos).*',
                 'urn:nasa:pds:maven.iuvs.raw:transition': 'mvn_iuv_l1a_(early|APP|comet).*',
                 'urn:nasa:pds:maven.iuvs.calibrated:calibration': 'mvn_iuv_l1b_(centroid|star).*',
                 'urn:nasa:pds:maven.iuvs.calibrated:corona': 'mvn_iuv_l1b_(outbound|inbound|inspace|outspace|incorona|outcorona).*',
                 'urn:nasa:pds:maven.iuvs.calibrated:cruise': 'mvn_iuv_l1b_(ISON|IPH|cruisecal).*',
                 'urn:nasa:pds:maven.iuvs.calibrated:disk': 'mvn_iuv_l1b_(apoapse|outdisk|indisk).*',
                 'urn:nasa:pds:maven.iuvs.calibrated:echelle': 'mvn_iuv_l1b_.*ech.*',
                 'urn:nasa:pds:maven.iuvs.calibrated:limb': 'mvn_iuv_l1b_(periapse|outlimb|inlimb).*',
                 'urn:nasa:pds:maven.iuvs.calibrated:occultation': 'mvn_iuv_l1b_occultation.*',
                 'urn:nasa:pds:maven.iuvs.calibrated:transition': 'mvn_iuv_l1b_(early|APP|comet).*',
                 'urn:nasa:pds:maven.iuvs.calibrated:phobos': 'mvn_iuv_l1b_(phobos).*',
                 'urn:nasa:pds:maven.iuvs.processed:corona': 'mvn_iuv_l1c_(outbound|inbound|corona|inspace|outspace|incorona|outcorona).*',
                 'urn:nasa:pds:maven.iuvs.processed:disk': 'mvn_iuv_l1c_apoapse.*',
                 'urn:nasa:pds:maven.iuvs.processed:echelle': 'mvn_iuv_l1c_.*ech.*',
                 'urn:nasa:pds:maven.iuvs.processed:occultation': 'mvn_iuv_l1c_occultation.*',
                 'urn:nasa:pds:maven.iuvs.processed:transition': 'mvn_iuv_l1c_(early|APP|comet).*',
                 'urn:nasa:pds:maven.iuvs.processed:phobos': 'mvn_iuv_l1c_(phobos).*',
                 'urn:nasa:pds:maven.iuvs.processed:limb': 'mvn_iuv_l1c_(periapse|outlimb|inlimb).*',
                 'urn:nasa:pds:maven.iuvs.derived:corona': 'mvn_iuv_l2_(outbound|inbound|inspace|outspace|incorona|outcorona).*',
                 'urn:nasa:pds:maven.iuvs.derived:cruise': 'mvn_iuv_l2_(checkout|ISON|IPH|cruisecal).*',
                 'urn:nasa:pds:maven.iuvs.derived:disk': 'mvn_iuv_l2_apoapse.*',
                 'urn:nasa:pds:maven.iuvs.derived:echelle': 'mvn_iuv_l2_.*ech.*',
                 'urn:nasa:pds:maven.iuvs.derived:limb': 'mvn_iuv_l2_periapse.*',
                 'urn:nasa:pds:maven.iuvs.derived:occultation': 'mvn_iuv_l2_occultation.*',
                 'urn:nasa:pds:maven.iuvs.derived:transition': 'mvn_iuv_l2_(early|APP|comet).*',
                 'urn:nasa:pds:maven.iuvs.derived:phobos': 'mvn_iuv_l2_(phobos).*',
                 }},
    'iuv_meta':
        {'lid': {  # Metadata LID mapping
            'urn:nasa:pds:maven.iuvs.calibrated:corona': 'mvn_iuv_calibrated_collection_corona.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:cruise': 'mvn_iuv_calibrated_collection_cruise.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:disk': 'mvn_iuv_calibrated_collection_disk.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:echelle': 'mvn_iuv_calibrated_collection_echelle.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:limb': 'mvn_iuv_calibrated_collection_limb.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:occultation': 'mvn_iuv_calibrated_collection_occultation.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:transition': 'mvn_iuv_calibrated_collection_transition.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:phobos': 'mvn_iuv_calibrated_collection_phobos.*',
                   'urn:nasa:pds:maven.iuvs.calibrated:calibration': 'mvn_iuv_calibrated_collection_calibration.*',
                   'urn:nasa:pds:maven.iuvs.calibrated': 'mvn_iuv_calibrated_bundle.*',
                   'urn:nasa:pds:maven.iuvs.derived:corona': 'mvn_iuv_derived_collection_corona.*',
                   'urn:nasa:pds:maven.iuvs.derived:cruise': 'mvn_iuv_derived_collection_cruise.*',
                   'urn:nasa:pds:maven.iuvs.derived:disk': 'mvn_iuv_derived_collection_disk.*',
                   'urn:nasa:pds:maven.iuvs.derived:echelle': 'mvn_iuv_derived_collection_echelle.*',
                   'urn:nasa:pds:maven.iuvs.derived:limb': 'mvn_iuv_derived_collection_limb.*',
                   'urn:nasa:pds:maven.iuvs.derived:occultation': 'mvn_iuv_derived_collection_occultation.*',
                   'urn:nasa:pds:maven.iuvs.derived:transition': 'mvn_iuv_derived_collection_transition.*',
                   'urn:nasa:pds:maven.iuvs.derived:phobos': 'mvn_iuv_derived_collection_phobos.*',
                   'urn:nasa:pds:maven.iuvs.derived': 'mvn_iuv_derived_bundle.*',
                   'urn:nasa:pds:maven.iuvs.processed:corona': 'mvn_iuv_processed_collection_corona.*',
                   'urn:nasa:pds:maven.iuvs.processed:disk': 'mvn_iuv_processed_collection_disk.*',
                   'urn:nasa:pds:maven.iuvs.processed:echelle': 'mvn_iuv_processed_collection_echelle.*',
                   'urn:nasa:pds:maven.iuvs.processed:limb': 'mvn_iuv_processed_collection_limb.*',
                   'urn:nasa:pds:maven.iuvs.processed:occultation': 'mvn_iuv_processed_collection_occultation.*',
                   'urn:nasa:pds:maven.iuvs.processed:transition': 'mvn_iuv_processed_collection_transition.*',
                   'urn:nasa:pds:maven.iuvs.processed:phobos': 'mvn_iuv_processed_collection_phobos.*',
                   'urn:nasa:pds:maven.iuvs.processed:schema': 'mvn_iuv_processed_collection_schema.*',
                   'urn:nasa:pds:maven.iuvs.processed:document': 'mvn_iuv_processed_collection_document.*',
                   'urn:nasa:pds:maven.iuvs.processed:context': 'mvn_iuv_processed_collection_context.*',
                   'urn:nasa:pds:maven.iuvs.processed': 'mvn_iuv_processed_bundle.*',
                   'urn:nasa:pds:maven.iuvs.raw:corona': 'mvn_iuv_raw_collection_corona.*',
                   'urn:nasa:pds:maven.iuvs.raw:cruise': 'mvn_iuv_raw_collection_cruise.*',
                   'urn:nasa:pds:maven.iuvs.raw:disk': 'mvn_iuv_raw_collection_disk.*',
                   'urn:nasa:pds:maven.iuvs.raw:echelle': 'mvn_iuv_raw_collection_echelle.*',
                   'urn:nasa:pds:maven.iuvs.raw:limb': 'mvn_iuv_raw_collection_limb.*',
                   'urn:nasa:pds:maven.iuvs.raw:calibration': 'mvn_iuv_raw_collection_calibration.*',
                   'urn:nasa:pds:maven.iuvs.raw:occultation': 'mvn_iuv_raw_collection_occultation.*',
                   'urn:nasa:pds:maven.iuvs.raw:phobos': 'mvn_iuv_raw_collection_phobos.*',
                   'urn:nasa:pds:maven.iuvs.raw:transition': 'mvn_iuv_raw_collection_transition.*',
                   'urn:nasa:pds:maven.iuvs.raw': 'mvn_iuv_raw_bundle.*', }},

    # Key Parameters: In situ and IUVS
    'kp':
        {'lid': {'urn:nasa:pds:maven.kp.calibrated:data.kp': 'mvn_kp_insitu_kp'}},

    # Langmuri Probe and Waves
    'lpw':
        {'lid': {'urn:nasa:pds:maven.lpw.calibrated:data.lp.iv': 'mvn_lpw_l2_lpiv',
                 'urn:nasa:pds:maven.lpw.calibrated:data.mgr.scpot': 'mvn_lpw_l2_mgrscpot',
                 'urn:nasa:pds:maven.lpw.calibrated:data.w.e12': 'mvn_lpw_l2_we12',
                 'urn:nasa:pds:maven.lpw.calibrated:data.w.e12bursthf': 'mvn_lpw_l2_we12bursthf',
                 'urn:nasa:pds:maven.lpw.calibrated:data.w.e12burstlf': 'mvn_lpw_l2_we12burstlf',
                 'urn:nasa:pds:maven.lpw.calibrated:data.w.e12burstmf': 'mvn_lpw_l2_we12burstmf',
                 'urn:nasa:pds:maven.lpw.calibrated:data.w.specact': 'mvn_lpw_l2_wspecact',
                 'urn:nasa:pds:maven.lpw.calibrated:data.w.specpas': 'mvn_lpw_l2_wspecpas',
                 'urn:nasa:pds:maven.lpw.derived:data.lp.nt': 'mvn_lpw_l2_lpnt',
                 'urn:nasa:pds:maven.lpw.derived:data.mrg.exb': 'mvn_lpw_l2_mrgexb',
                 'urn:nasa:pds:maven.lpw.derived:data.w.n': 'mvn_lpw_l2_wn',
                 'urn:nasa:pds:maven.lpw.raw:data.act': 'mvn_lpw_l0b_act',
                 'urn:nasa:pds:maven.lpw.raw:data.actspechf': 'mvn_lpw_l0b_actspechf',
                 'urn:nasa:pds:maven.lpw.raw:data.actspeclf': 'mvn_lpw_l0b_actspeclf',
                 'urn:nasa:pds:maven.lpw.raw:data.actspecmf': 'mvn_lpw_l0b_actspecmf',
                 'urn:nasa:pds:maven.lpw.raw:data.adr': 'mvn_lpw_l0b_adr',
                 'urn:nasa:pds:maven.lpw.raw:data.atr': 'mvn_lpw_l0b_atr',
                 'urn:nasa:pds:maven.lpw.raw:data.euv': 'mvn_lpw_l0b_euv',
                 'urn:nasa:pds:maven.lpw.raw:data.hsbmhf': 'mvn_lpw_l0b_hsbmhf',
                 'urn:nasa:pds:maven.lpw.raw:data.hsbmlf': 'mvn_lpw_l0b_hsbmlf',
                 'urn:nasa:pds:maven.lpw.raw:data.hsbmmf': 'mvn_lpw_l0b_hsbmmf',
                 'urn:nasa:pds:maven.lpw.raw:data.hsk': 'mvn_lpw_l0b_hsk',
                 'urn:nasa:pds:maven.lpw.raw:data.pas': 'mvn_lpw_l0b_pas',
                 'urn:nasa:pds:maven.lpw.raw:data.passpechf': 'mvn_lpw_l0b_passpechf',
                 'urn:nasa:pds:maven.lpw.raw:data.passpeclf': 'mvn_lpw_l0b_passpeclf',
                 'urn:nasa:pds:maven.lpw.raw:data.passpecmf': 'mvn_lpw_l0b_passpecmf',
                 'urn:nasa:pds:maven.lpw.raw:data.swp1': 'mvn_lpw_l0b_swp1',
                 'urn:nasa:pds:maven.lpw.raw:data.swp2': 'mvn_lpw_l0b_swp2'}},

    # Magnetometer
    'mag':
        {'lid': {'urn:nasa:pds:maven.mag.:data.': 'mvn_mag_'}},

    # NGIMS
    'ngi':
        {'lid': {'urn:nasa:pds:maven.pfp.:data.': 'mvn_ngi.*'}},

    # Particles and Fields
    'pfp':
        {'lid': {'urn:nasa:pds:maven.pfp.:data.': 'mvn_pfp_'}},

    # SEP
    'sep':
        {'lid': {'urn:nasa:pds:maven.sep.ancillary:data': 'mvn_sep_l2_anc',
                 'urn:nasa:pds:maven.sep.calibrated:data.spec': 'mvn_sep_l2_cal-eflux-svy',
                 'urn:nasa:pds:maven.sep.reduced:data.counts': 'mvn_sep_l1_counts'}},

    # Static
    'sta':
        {'lid': {'urn:nasa:pds:maven.static.c:data.2a_hkp': 'mvn_sta_l2_2a-hkp',
                 'urn:nasa:pds:maven.static.c:data.c0_64e2m': 'mvn_sta_l2_c0-64e2m',
                 'urn:nasa:pds:maven.static.c:data.c2_32e32m': 'mvn_sta_l2_c2-32e32m',
                 'urn:nasa:pds:maven.static.c:data.c4_4e64m': 'mvn_sta_l2_c4-4e64m',
                 'urn:nasa:pds:maven.static.c:data.c6_32e64m': 'mvn_sta_l2_c6-32e64m',
                 'urn:nasa:pds:maven.static.c:data.c8_32e16m': 'mvn_sta_l2_c8-32e16m',
                 'urn:nasa:pds:maven.static.c:data.ca_16e4d16a': 'mvn_sta_l2_ca-16e4d16a',
                 'urn:nasa:pds:maven.static.c:data.cc_32e8d32m': 'mvn_sta_l2_cc-32e8d32m',
                 'urn:nasa:pds:maven.static.c:data.cd_32e8d32m': 'mvn_sta_l2_cd-32e8d32m',
                 'urn:nasa:pds:maven.static.c:data.ce_16e4d16a16m': 'mvn_sta_l2_ce-16e4d16a16m',
                 'urn:nasa:pds:maven.static.c:data.cf_16e4d16a16m': 'mvn_sta_l2_cf-16e4d16a16m',
                 'urn:nasa:pds:maven.static.c:data.d0_32e4d16a8m': 'mvn_sta_l2_d0-32e4d16a8m',
                 'urn:nasa:pds:maven.static.c:data.d1_32e4d16a8m': 'mvn_sta_l2_d1-32e4d16a8m',
                 'urn:nasa:pds:maven.static.c:data.d2_32e16a8m': 'mvn_sta_l2_d2-32e16a8m',
                 'urn:nasa:pds:maven.static.c:data.d3_32e16a8m': 'mvn_sta_l2_d3-32e16a8m',
                 'urn:nasa:pds:maven.static.c:data.d4_4d16a2m': 'mvn_sta_l2_d4-4d16a2m',
                 'urn:nasa:pds:maven.static.c:data.d6_events': 'mvn_sta_l2_d6-events',
                 'urn:nasa:pds:maven.static.c:data.d7_fsthkp': 'mvn_sta_l2_d7-fsthkp',
                 'urn:nasa:pds:maven.static.c:data.d8_l2r': 'mvn_sta_l2_d8-l2r',
                 'urn:nasa:pds:maven.static.c:data.d9_l2r64e': 'mvn_sta_l2_d9-l2r64e',
                 'urn:nasa:pds:maven.static.c:data.da_lr': 'mvn_sta_l2_da-lr',
                 'urn:nasa:pds:maven.static.c:data.db_1024tof': 'mvn_sta_l2_db-1024tof'}},

    # SWEA
    'swe':
        {'lid': {'urn:nasa:pds:maven.swea.calibrated:data.arc_3d': 'mvn_swe_l2_arc3d',
                 'urn:nasa:pds:maven.swea.calibrated:data.arc_pad': 'mvn_swe_l2_arcpad',
                 'urn:nasa:pds:maven.swea.calibrated:data.arc_spec': 'mvn_swe_l2_arcspec',
                 'urn:nasa:pds:maven.swea.calibrated:data.svy_3d': 'mvn_swe_l2_svy3d',
                 'urn:nasa:pds:maven.swea.calibrated:data.svy_pad': 'mvn_swe_l2_svypad',
                 'urn:nasa:pds:maven.swea.calibrated:data.svy_spec': 'mvn_swe_l2_svyspec'}},
    # SWIA
    'swi':
        {'lid': {'urn:nasa:pds:maven.swia.calibrated:data.coarse_arc_3d': 'mvn_swi_l2_coarsearc3d',
                 'urn:nasa:pds:maven.swia.calibrated:data.coarse_svy_3d': 'mvn_swi_l2_coarsesvy3d',
                 'urn:nasa:pds:maven.swia.calibrated:data.fine_arc_3d': 'mvn_swi_l2_finearc3d',
                 'urn:nasa:pds:maven.swia.calibrated:data.fine_svy_3d': 'mvn_swi_l2_finesvy3d',
                 'urn:nasa:pds:maven.swia.calibrated:data.onboard_svy_mom': 'mvn_swi_l2_onboardsvymom',
                 'urn:nasa:pds:maven.swia.calibrated:data.onboard_svy_spec': 'mvn_swi_l2_onboardsvyspec'}}}

filename_time_format = '%Y-%m-%d-%H-%M-%S'
